config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'reviews/controller'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only:[:show] do
    resources :bookings, only:[:index]
  end

  resources :wearables  do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create, :edit, :update]
    #dont forget patch
  end

  resources :bookings, only:[:edit, :update, :show] do
    resources :payments, only: [:new]
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :wearable
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :start_date, :end_date, :status, presence: true  #status = pending | current | closed |
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  def new
    @wearable = Wearable.find_by_id(params[:wearable_id])
    authorize @wearable
    @booking = Booking.new
    @bookings_for_wearable = Booking.where(wearable: @wearable, status: 'confirmed')
  end

  def create
    @wearable = Wearable.find_by_id(params[:wearable_id])
    authorize @wearable
    @booking = Booking.new(params_booking)
    @booking.status = "pending"
    @booking.user = current_user
    @booking.wearable = @wearable

    price_object = Stripe::Price.create({
      unit_amount: @wearable.price_cents,
      currency: 'eur',
      product: @wearable.stripe_id,
    })

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      mode: 'payment',
      line_items: [{
        price: price_object,
        quantity: 1
      }],
      success_url: "https://wearables-app.herokuapp.com/wearables",
      cancel_url: "https://wearables-app.herokuapp.com/wearables"
    )
    if @booking.save
      @booking.update(checkout_session_id: session.id)
      redirect_to new_booking_payment_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @bookings = policy_scope(Booking)
    @bookings = Booking.where(user: current_user)
    w = Wearable.where(user: current_user)
    w.each do |wearable|
      @bookings += Booking.where(wearable: wearable)
    end

  end

  def edit
    @booking = Booking.find_by_id(params[:id])
    authorize @booking
    raise
  end

  def update
    @booking = Booking.find_by_id(params[:id])
    authorize @booking
    @booking.update(status: params[:status]) if params[:status]
    redirect_to user_bookings_path(current_user)
  end

  def show
    @booking = Booking.find_by_id(params[:id])
    authorize @booking
    @wearable = @booking.wearable
    authorize @wearable
  end


  private

  def params_booking
    params.require(:booking).permit(:start_date, :end_date, :wearable_id)
  end

end

app/views/bookings/index.html.erb
<div class="container my-3 d-flex flex-column align-items-center">
  <h1 class="my-3">My bookings</h1>
  <div class= "w-75">
    <% @bookings.each do |booking| %>
      <% color = ""  %>
      <% needsButton = false  %>
      <% if (booking.status == "unconfirmed" && booking.user == current_user) %>
        <% color = "border-info" %>
      <% elsif booking.status == "unconfirmed" %>
        <% needsButton = true %>
        <% color = "border-warning" %>
      <% elsif booking.status == "confirmed" %>
        <% color = "border-success" %>
      <% else %>
        <% color = "border-secondary" %>
      <% end %>
      <div class="my-4 mx-5 border-start border-5 <%= color %> p-3 position-relative bg-light ">
        <div class="d-flex px-3">
          <h5>Booking from:</h5>
          <h5 class="mx-3"><strong><%= booking.wearable.user == current_user ? "You" : booking.wearable.user.username %></strong></h5>
        </div>
        <div class="d-flex px-3">
          <h5>Item:</h5>
          <h5 class="mx-3"><strong><%= booking.wearable.title %></strong></h5>
        </div>
        <div class="d-flex px-3">
          <h5>Booking to:</h5>
          <h5 class="mx-3"><strong><%= booking.user == current_user ? "You" : booking.user.username %></strong></h5>
        </div>
        <div class="d-flex px-3">
          <h5>Status:</h5>
          <h5 class="mx-3"><strong><%= booking.status %></strong></h5>
        </div>
        <div class="d-flex px-3">
          <h5>From:</h5>
          <h5 class="mx-3"><strong><%= (booking.start_date).to_s[0..9] %></strong></h5>
        </div>

        <div class="d-flex px-3">
          <h5>Until:</h5>
          <h5 class="mx-3"><strong><%= (booking.end_date).to_s[0..9] %></strong></h5>
        </div>
        <div class="position-absolute end-0 top-0">
          <div class="d-flex m-5">
            <%= cl_image_tag booking.wearable.photos[0].key, height: 150, width: 150, radius: 10 %>
          </div>
        </div>
        <% if needsButton  %>
              <div class="d-flex justify-content-around position-relative py-2">

                <div class="d-flex flex-column justify-content-center align-items-center  w-50 mx-3 py-2">
                  <%= link_to "Confirm Booking",booking_path(booking, {status: "confirmed"}), class: "btn btn-ghost",data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to confirm?"} %>
                </div>

                <div class="d-flex flex-column  w-50 mx-3 justify-content-center align-items-center py-2">
                  <%= link_to "Reject Booking",booking_path(booking, {status: "rejected"}),class: "btn btn-ghost" ,data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to reject?"} %>
                </div class="">
              </div>
          <% end  %>
      </div>
    <% end  %>
  </div>


</div>

app/views/bookings/new.html.erb
<div class="container col-4">
  <div id='flat-booking-dates' data-unavailable="<%= @wearable.unavailable_dates.to_json %>">

        <%= simple_form_for([@wearable, @booking]) do |f| %>
            <%= f.input :start_date, as: :string, type: :text %>
            <%= f.input :end_date, as: :string, type: :text %>
            <%= f.submit "Book", class: "btn btn-primary" %>

      <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container d-flex">
  <div class = "w-25 flex-column bg-light">
    <h5>Wearable: <%= @booking.wearable.title %></h5>
    <h5>From: <%= ((@booking.start_date).to_s)[0..9] %></h5>
    <h5>To: <%= ((@booking.end_date).to_s)[0..9] %></h5>
    <% days = ((@booking.end_date - @booking.start_date)/(24 * 60**2)).to_i  %>
    <% p = @wearable.price  %>
    <% total = p*days  %>
    <h5> <%="#{days} days x #{p} = #{total}" %></h5>
  </div>
  <div class=" w-25 d-flex bg-primary">
    Pay
  </div>

</div>