config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'reviews/controller'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only:[:show] do
    resources :bookings, only:[:index]
  end

  resources :wearables  do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create, :edit, :update]
    #dont forget patch
  end

  resources :bookings, only:[:edit, :update, :show] do
    resources :payments, only: [:new]
  end

end

app/views/shared/_navbar.html.erb
<nav class="border-bottom sticky shadow-sm background">
  <div class="container d-flex justify-content-between p-3">
    <div class="d-flex">
      <%= image_tag("wearable.png", size: "170x50", class:"navbar-img") %>
      <a class="d-flex align-items-center text-decoration-none me-5" href="/">Home</a>
      <a class="d-flex align-items-center text-decoration-none" href="/wearables" >Browse</a>
    </div>

    <div>
      <%= form_with url: wearables_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a wearable"
      %>
      <%= submit_tag "Search", class: "btn btn-secondary" %>
    <% end %>
    </div>
    <div class="d-inline-flex">
      <span class="d-flex align-items-center mx-3"><%= current_user.email  if user_signed_in? %></span>
        <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Menu
        </button>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
          <li><a class="dropdown-item" <%= 'href='+"/users/#{current_user.id if current_user }"%> href="/users/">My account</a></li>
          <li><a class="dropdown-item" href=<%=(user_bookings_path(current_user) if current_user)%> >My bookings</a></li>
          <li><a class="dropdown-item" href=<%=(edit_user_registration_path(current_user) if current_user)%> >Edit your details</a></li>
          <li><%= link_to "sign-out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %></li>
          <% else %>
          <li><a class="dropdown-item" href=<%=new_user_session_path(current_user)%> >Sign in</a></li>
          <li><a class="dropdown-item" href=<%=new_user_registration_path(current_user)%> >Register</a></li>
          <% end %>
        </ul>
      </div>

    </div>
    </div>
  </div>
</nav>