config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'reviews/controller'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only:[:show] do
    resources :bookings, only:[:index]
  end

  resources :wearables  do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create, :edit, :update]
    #dont forget patch
  end

  resources :bookings, only:[:edit, :update, :show] do
    resources :payments, only: [:new]
  end

end

app/models/wearable.rb
class Wearable < ApplicationRecord
  monetize :price_cents

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :brand, :category, :price, :description, :title, :size, :photos, :address, presence: true
  validates :category, inclusion: { in: ["watch", "jacket", "glasses"] }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description, :category ],
    using: { tsearch: { prefix: true } }
end

app/controllers/wearables_controller.rb
require 'json'

class WearablesController < ApplicationController

  def index
    @wearables = policy_scope(Wearable)

    if params[:query].present?
      @wearables = Wearable.search_by_title_and_description(params[:query])
    else
      @wearables = Wearable.all
    end

    @markers = @wearables.geocoded.map do |wearable|
      {
        lat: wearable.latitude,
        lng: wearable.longitude,
        info_window: render_to_string(partial: "info_window", locals: {wearable: wearable}),
        image_url: helpers.asset_url("logo.png")
      }
    end
  end

  def new
    @wearable = Wearable.new
    authorize @wearable
  end

  def edit
    @wearable = Wearable.find(params[:id])
    authorize @wearable
  end

  def show
    @wearable = Wearable.find_by_id(params[:id])
    authorize @wearable
    @review = Review.new
    @bookings = Booking.where(wearable: @wearable)
    @reviews = @bookings.map {|b| b.reviews }.reject {|r| r.nil? }.flatten
    @markers = [{
      lat: @wearable.geocode[0],
      lng: @wearable.geocode[1],
      info_window: render_to_string(partial: "info_window", locals: {wearable: @wearable}),
      image_url: helpers.asset_url("logo.png")
    }]
  end

  def update
    @wearable = Wearable.find(params[:id])
    @wearable.update(params_wearable)
    authorize @wearable
    if @wearable.save
      redirect_to wearable_path(@wearable)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create
    @wearable = Wearable.new(params_wearable)
    authorize @wearable
    sid = Stripe::Product.create({name: @wearable.title})
    sid = sid.to_s
    sid = JSON.parse(sid)
    @wearable.stripe_id = sid["id"]
    @wearable.user = current_user


    if @wearable.save
      redirect_to wearable_path(@wearable)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @wearable = Wearable.find(params[:id])
    authorize @wearable
    @wearable.destroy!
    redirect_to wearables_path, status: :see_other
  end

  private

  def params_wearable
    params.require(:wearable).permit(:title, :description, :brand, :category, :size, :address, :price, photos: [])
  end

end

app/views/wearables/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide carousel-dark" data-bs-ride="carousel">
  <div class="carousel-inner">
      <% @wearable.photos.each do |p| %>
        <% if p == @wearable.photos[0] %>
          <div class="carousel-item active">
        <% else %>
          <div class="carousel-item">
        <% end %>
        <%= cl_image_tag p.key, height: 600, width: 550, crop: :fill, class: "rounded-4" %>
        </div>
      <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/wearables/_info_window.html.erb
<div class="ps-3 card-details">
  <div>
    <h5 class= "pe-3 pt-3"> <strong> <%= wearable.title %> </strong></h5>
  </div>
</div>
<%= cl_image_tag wearable.photos[0].key, height: 200, width: 130, crop: :fill %>
</div>

app/views/wearables/_review.html.erb
<span>
  <% (0...(review.rating)).each do %>
    <i class="fa fa-star" aria-hidden="true"></i>
  <% end %>
</span>
<p><%= review.content %></p>

app/views/wearables/edit.html.erb
<%= simple_form_for(@wearable) do |f| %>
  <%= f.input :title, as: :string %>

  <%= f.input :photos, as: :file, input_html: { multiple: true } %>

  <%= f.input :description, as: :string %>

  <%= f.input :size, as: :string %>

  <%= f.input :brand, as: :string %>

  <%= f.input :category, as: :string %>

  <%= f.input :price, as: :float %>


  <%= f.submit "Submit"%>

<% end %>

app/views/wearables/index.html.erb
<div class="container">
<div class="container d-flex justify-content-between align-items-center my-4">
<h1>Discover Wearables</h1>
<h5><%= link_to "Add Wearable", new_wearable_path, class: "btn btn-primary" %></h5>
</div>

<div class="d-flex justify-content-around align-self-center mb-5">
  <div style="width: 100%; height: 400px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    class="rounded-5 shadow">
  </div>
</div>


  <div class="row row-cols-auto">
      <% @wearables.each do |w| %>
        <%= link_to wearable_path(w) do %>
          <div class="card-design col m-3 pe-0">
            <div class="ps-3 card-details">
              <div>
                <h5 class= "pe-3 pt-3"> <strong> <%= w.title %> </strong></h5>
                <h4> category: <%= w.category %></h4>
                <h4> brand: <%= w.brand %></h4>
              </div>
              <h4 class="pb-3"> <strong> €<%= w.price.round %>/day </strong></h4>
            </div>
            <%= cl_image_tag w.photos[0].key, height: 200, width: 130, crop: :fill %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/wearables/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-6 ">
      <%= simple_form_for(@wearable) do |f| %>
        <%= f.input :title, as: :string %>

        <%= f.input :photos, as: :file, input_html: { multiple: true } %>

        <%= f.input :description, as: :string %>

        <%= f.input :size, as: :select, collection: ['S', 'M', 'L', 'XL'] %>

        <%= f.input :brand, as: :string %>

        <%= f.input :category, as: :select, collection: ['watch', 'jacket', 'glasses'] %>

        <%= f.input :price, as: :float %>

        <%= f.input :address, as: :string %>

        <%= f.submit "Submit"%>

      <% end %>
    </div>
  </div>
</div>

app/views/wearables/show.html.erb
<div data-controller="review">
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-xl-5 bg-white shadow rounded-4 m-3 p-4 d-flex flex-column justify-content-between">
        <div>
          <h2> <strong><%= @wearable.title %> </strong></h2>
          <h5 class="mt-4 mb-4"> <%= @wearable.description %> </h5>
          <div class="d-flex"><h5 class="text-muted"> offered by: </h5>  <h5  class="mx-2"> <strong><%= @wearable.user.username%> </strong> </h5> </div>
          <div class="d-flex"><h5 class="text-muted"> size: </h5><h5 class="mx-2"><%= @wearable.size %> </h5> </div>
          <div class="d-flex"><h5 class="text-muted"> brand: </h5><h5 class="mx-2"><%= @wearable.brand %> </h5></div>
          <div class="d-flex"><h5 class="text-muted"> category: </h5><h5 class="mx-2"><%= @wearable.category %> </h5></div>
          <div class="d-flex"><h5 class="text-muted"> price: </h5><h5 class="mx-2">€<%= @wearable.price.round() %>/day </h5></div>
        </div>
        <div>
          <div class="d-flex justify-content-between">
            <%= link_to "Book it!", new_wearable_booking_path(@wearable), class: "btn btn-primary m-0 mx-0"  %>
            <div class="d-flex">
            <%= link_to "Edit", edit_wearable_path(@wearable), class: "me-1 d-flex align-items-center text-decoration-underline link-secondary" if policy(@wearable).edit? %>
            <%= link_to "Delete", wearable_path(@wearable), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: " d-flex align-items-center text-decoration-underline link-secondary ms-1" if policy(@wearable).edit? %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-5 bg-white shadow rounded-4 m-3 p-0 align-self-center">
          <div style="width: 100%; height: 500px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            class="rounded-4">
          </div>

      </div>
      <div  class="col-xl-5  bg-white shadow rounded-4 m-3 p-4" data-controller="insert-in-list">
          <div data-insert-in-list-target="items">
            <h2> <strong> Last 4 Reviews </strong></h2>
            <% @reviews.last(4).each do |review| %>
            <%  %>
              <%= render 'review', review: review %>
            <% end %>
          </div>
          <h2> <strong> Add your review </strong></h2>
          <%= render 'reviews/form', wearable: @wearable, review: @review %>
      </div>
      <div class="col-xl-5 bg-white shadow rounded-4 m-3 p-0 justify-content-center" style="height: 600px;">
      <%= render 'carousel' %>
      </div>

    </div>
  </div>
</div>